name: Python package

on:
  push:
    branches:
      - main
      - develop
    # Add more branches if needed
  pull_request:
    branches:
      - main
      - develop
    # Add more branches if needed

jobs:
  lint:
    name: Lint with pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pylint
        pip install -r requirements.txt  # Install project dependencies

    - name: Run pylint
      run: |
        pylint area.py test_area.py  # Specify the files or directories to lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install project dependencies
        pip install pytest  # Install pytest

    - name: Run tests
      run: |
        pytest  # Run tests using pytest
